# Generated by Django 5.2 on 2025-04-19 14:46

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attachments", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=256, verbose_name="subject")),
                ("body", models.CharField(max_length=8096, verbose_name="body")),
                (
                    "recipient",
                    models.EmailField(max_length=254, verbose_name="recipient"),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled time"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "public_key",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="public key"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Sent"),
                            (3, "Failed"),
                            (4, "Unknown"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True, related_name="mails", to="attachments.attachment"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail",
                "verbose_name_plural": "Mails",
            },
        ),
        migrations.CreateModel(
            name="CarbonCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_copies",
                        to="mailer.mail",
                        verbose_name="mail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carbon Copy",
                "verbose_name_plural": "Carbon Copies",
            },
        ),
    ]
