# Generated by Django 5.2 on 2025-04-20 17:01

import attachments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttachmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "main_type",
                    models.CharField(max_length=256, verbose_name="main_type"),
                ),
                ("sub_type", models.CharField(max_length=256, verbose_name="sub_type")),
            ],
            options={
                "verbose_name": "Attachment Type",
                "verbose_name_plural": "Attachment Types",
                "unique_together": {("main_type", "sub_type")},
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "public_key",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="public key"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "file",
                    models.FileField(
                        max_length=1024,
                        upload_to=attachments.models.attachment_upload_to,
                        verbose_name="file",
                    ),
                ),
                (
                    "attachment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="attachments.attachmenttype",
                        verbose_name="Attachment Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
    ]
